services:
  # Backend API (Laravel)
  backend:
    build:
      context: ./backend
    container_name: vault-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/var/www

  # Frontend SPA (Vue)
  frontend:
    build:
      context: ./frontend
    container_name: vault-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules